### ISSUE TITLE
Set up backend CI/CD

### ISSUE THREAD

**Issue by irithsharma** [passiondynamics/cineguess-backend#1]
**Points:** 3

**TODOs:**
- [x] Add test stage
  - [x] Run unit tests
  - [x] Run integration tests
- [x] Add build stage
- [x] Add deploy stage
- [x] Validate that pipeline works as expected

**Description:** Implement initial pipeline to build backend artifact, run tests, and deploy to cloud service.

**Notes:** n/a
